language: php

sudo: false

php:
  - 7.3
  - 7.4

install:
    - composer update --prefer-stable --prefer-dist --no-interaction

script:
  - composer lint
  - composer install
  - composer test
  - composer stan
